### ISSUE TITLE
Bunnyhopping plugin not working properly

### ISSUE THREAD

**Issue by Alfie94** [AnAkkk/TFTrue#10]
You can bunnyhop but you have to fall off a height and then bhop. Just jumping off the floor pushes you back to the floor.

**Comment by sapphonie** [comment]
Bhop currently crashes. Offsets need updated most likely

**Comment by AnAkkk** [comment]
Is this broken both on Windows and Linux, or only one of them?

**Comment by sapphonie** [comment]
both

**Comment by AnAkkk** [comment]
Fixed in https://github.com/AnAkkk/TFTrue/commit/6d9fe6327dbde8fdc218904bc76d5978fcd36607
