### ISSUE TITLE
Stop defaulting `tftrue_no_hats` to 1

### ISSUE THREAD

**Issue by Wiethoofd** [AnAkkk/TFTrue#11]
A lot of users don't realize that `tftrue_no_hats` defaults to 1, causing hats to be disabled and blame whitelists, setting it to 0 would make more sense, so it's entirely up to the user/server owner to configure TFTrue and disable hats/cosmetics, set whitelists etc.

**Comment by AnAkkk** [comment]
Can you create a PR?

**Comment by ldesgoui** [comment]
Can be closed by the way

**Comment by Wiethoofd** [comment]
Not sure the build you download on the [website](http://tftrue.esport-tools.net/) have this fix in them yet, documentation there at least is still out of date.

**Comment by AnAkkk** [comment]
The build hasn't been updated for a while, but I will try to get it updated once I have time to fix some of the broken features (mainly on Windows).
