### ISSUE TITLE
Control logging of Allowing and Disabling items

### ISSUE THREAD

**Issue by dhalucario** [AnAkkk/TFTrue#13]
Please add a variable that lets us disable the logging of enabled and disabled items.

**Comment by garrappachc** [comment]
Wonderful idea, I can start writing it and push a pull request this week if no one is already working on it :)

**Comment by dhalucario** [comment]
Doesn't seem like anyone is working on it. I was using TFTrue on my Pterodactyl game panel and apparently the output mass is so big that the panels spam protection is kicking in. Maybe we could generally unify the output of an item into a big single message instead of hundreds of smaller ones.

**Comment by dhalucario** [comment]
@garrappachc So, how is it going?

**Comment by sapphonie** [comment]
A sourcemod extension for this already exists:

https://forums.alliedmods.net/showthread.php?t=195008

**Comment by dhalucario** [comment]
I see. Thank you.

**Comment by AnAkkk** [comment]
https://github.com/AnAkkk/TFTrue/commit/2bd126c9f3db39f1f414f9d71e71177fb57d54e6
