### ISSUE TITLE
changing sv_logfilename_format breaks log uploading

### ISSUE THREAD

**Issue by sapphonie** [AnAkkk/TFTrue#14]
see https://github.com/stephanieLGBT/rgl-server-resources/pull/12 , several users have reported various issues with uploading logs and tftrue, & this seems to be the cause. If I knew c++ I'd put together a pull request, but I don't quite have enough knowhow with the language to do that, sorry.

**Comment by AnAkkk** [comment]
Fixed in https://github.com/AnAkkk/TFTrue/commit/10ecc3ae71f1406f3e5a1349abedcaa59f11c004
