### ISSUE TITLE
Match paused status and durations as log lines output

### ISSUE THREAD

**Issue by Wiethoofd** [AnAkkk/TFTrue#17]
Currently TF2 servers do not log a (match) pause event in the logs.

Adding one similar to the medic uber duration one (triggered chargedeployed, empty_uber and chargeended (duration 6.2)), might be nice for manual log parsing to get accurate damage per minute calculations.

Most ideal obviously would be to log who triggered the (un)pause, or just make it a world event (`L 08/13/2020 - 21:30:50: World triggered "Pause_Start"`)

Medigun example log lines:
```
L 08/13/2020 - 21:33:30: "Player<1><[U:1:123]><Blue>" triggered "chargedeployed" (medigun "medigun")
L 08/13/2020 - 21:33:33: "Player<1><[U:1:123]><Blue>" triggered "empty_uber"
L 08/13/2020 - 21:33:33: "Player<1><[U:1:123]><Blue>" triggered "chargeended" (duration "3.2")
```
Suggestion for pause log lines:
```
L 08/13/2020 - 21:33:30: "Player<1><[U:1:123]><Blue>" triggered "matchpause"
L 08/13/2020 - 21:40:30: "Player<1><[U:1:123]><Blue>" triggered "matchunpause"
L 08/13/2020 - 21:40:30: World triggered "Pause_Length" (seconds "420.69")
```
The last one is similar to the `L 08/13/2020 - 21:45:30: World triggered "Round_Length" (seconds "91.26")` after a `Round_Win` and new scores get logged.

Additionally at the very end when the `Game_Over` gets triggered and the final scores get logged a total duration of all pauses combined could be outputted to the logs.

Probably should only be the case when log uploads are enabled or have it as a `tftrue_logs_pauses` CVar, similar to the accuracy/includebuffs.

**Comment by Wiethoofd** [comment]
Apparently F2's [supstats2](https://etf2l.org/forum/customise/topic-27485/page-1/) already does the following:
```
if (g_bIsPaused)
	LogToGame("World triggered \"Game_Paused\"");
else
	LogToGame("World triggered \"Game_Unpaused\"");
```
Matching that for consistency should help getting this added to logs.tf's parser hopefully.

Having the actual pause duration with it or the combined one at the end is not in supstats2.

**Comment by sapphonie** [comment]
todotodo
