### ISSUE TITLE
Latest TFTrue vers. not loading

### ISSUE THREAD

**Issue by sapphonie** [AnAkkk/TFTrue#22]
TFTrue has been reported by many players as being nonfunctional as of latest update:

https://www.teamfortress.tv/58387/tftrue-not-installing-on-my-server
#20

Can personally repro on Ubuntu 20.10 as well

**Comment by MaranRoseGIT** [comment]
Hey, I know i'm not the creator of this, but I got into contact with AnAkkk via Steam and he said he will be looking into it for the linux version! 
![image_2021-03-30_084129](https://user-images.githubusercontent.com/80443691/112990144-b91d5900-9133-11eb-88b0-c3ba14f0652c.png)
![image_2021-03-30_084149](https://user-images.githubusercontent.com/80443691/112990186-c5091b00-9133-11eb-8680-6bae61886f10.png)

**Comment by AnAkkk** [comment]
Hey, I've updated https://tftrue.esport-tools.net/TFTrue.zip and the auto updater should be fixed as well.
