### ISSUE TITLE
4.83 - GLIBC_2.33 not found

### ISSUE THREAD

**Issue by sapphonie** [AnAkkk/TFTrue#26]
Running latest vers-

```
plugin_load addons/TFTrue.so
 failed to dlopen /home/container/tf/addons/TFTrue.so error=/lib/i386-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /home/container/tf/addons/TFTrue.so)
 ```
 
 Breaks TFTrue inside docker containers and everywhere not running bleeding edge distros.
 
 glibc is
2.32 on ubuntu 20.10
2.28 on debian buster
2.27 on ubuntu 18.04 (what [pterodactyl's source engine docker image](https://quay.io/pterodactyl/core:source) runs on)

**Comment by AnAkkk** [comment]
Hey, could you check with this one https://github.com/AnAkkk/TFTrue/blob/new_build/release/TFTrue.so

**Comment by Arie** [comment]
That link gives me a 404, but I used this version from your recent travis build and that works, thanks!

https://github.com/AnAkkk/TFTrue/raw/92f0702f0c51ab2962a0972fa4be5745761380f4/release/TFTrue.so

**Comment by AnAkkk** [comment]
Yeah, I had to rebuild it again after my message, should be fine now :)

**Comment by sapphonie** [comment]
Travis build works for me, though i think the version in the 4.84 release on github is still broken as it's still throwing the same libc error

**Comment by AnAkkk** [comment]
Fixed now
