### ISSUE TITLE
Server unstable due to excessive logging.

### ISSUE THREAD

**Issue by kikaragyozov** [AnAkkk/TFTrue#3]
Have you considered adding a cvar to disable logging and logs.tf (Everything regarding logging) support altogether? My server is just not strong enough for logging and it spams my server console, making it unreadable.

Thank you for reading this, keep up the good work!

**Comment by AnAkkk** [comment]
As long as tftrue_logs_apikey is not set and you don't turn on logging on yourself in any config (with the log on command), then there should be no logging at all.

**Comment by kikaragyozov** [comment]
What is the cause of these messages: https://imgur.com/UitB72I
They appeared after installing TFTrue and your anti-cheat.

**Comment by AnAkkk** [comment]
These messages will only show up when logging is enabled (log on).
This is automatically enabled when tftrue_logs_apikey is set. Otherwise, you must have enabled it somewhere.

**Comment by kikaragyozov** [comment]
Current value of cvar "tftrue_logs_apikey" is "", I have not set logging up, yet they still appear. Any ideas?

**Comment by kikaragyozov** [comment]
I think I found the problem, I didn't think log on/log off is an actual command. Writing log off helped me fix the issue. Thank you!
