### ISSUE TITLE
TF2 update Oct 5 breaks TFTrue (yes, another one)

### ISSUE THREAD

**Issue by sapphonie** [AnAkkk/TFTrue#49]

**Comment by AnAkkk** [comment]
Seems linked to the auto updater somehow, it doesn't happen when it's disabled.

**Comment by sapphonie** [comment]
Fixed in https://github.com/AnAkkk/source-sdk-2013/pull/2 - a function was added to CBaseServer, causing all offsets to be off by one

**Comment by AnAkkk** [comment]
Fixed in https://github.com/AnAkkk/TFTrue/commit/bb00b27309a0f330496ff8728510ee5d9da6b4e8
