### ISSUE TITLE
my compile doesnt run on the server

### ISSUE THREAD

**Issue by jdlovins** [AnAkkk/TFTrue#5]
Hello there, I'm trying to compile your extension from source to change some things for my server. It comiles fine, but when i try to run it on srcds i get

undefined symbol: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_createERjj

Any idea what that means?

Thanks

**Comment by AnAkkk** [comment]
Which version of gcc/clang and libstdc++ did you try to compile it with?

**Comment by jdlovins** [comment]
I followed your travis build log thing basically, so gcc 4.9. I also tried with clang 3.7 and no luck.

How would i go about finding the libstdc++ version? I'm not really familiar with C++. Just trying to piece this together.

**Comment by jdlovins** [comment]
Pretty sure its libstdc++6, since thats what i had to install for the tf2 server.

**Comment by AnAkkk** [comment]
I think it is because ModuleScanner and FunctionRoute have been recompiled with gcc 5.x libstdc++, which has a new C++ ABI which is not compatible with the older ones. The binary file resulting in the travis build would probably have the same problem I guess.
Could you please try with a more recent version of gcc (5.x or 6.x)?

**Comment by jdlovins** [comment]
Installed gcc & g++ 5 and still a no go.
gcc (Ubuntu 5.3.0-3ubuntu1~14.04) 5.3.0 2015120
g++ (Ubuntu 5.3.0-3ubuntu1~14.04) 5.3.0 20151204

Do i need to change something in the make file? I updated the /usr/bin/gcc & g++ links to be /usr/bin/gcc-5 and g++-5 so it should have been compiled with the 5.3 version instead of 4.9

**Comment by jdlovins** [comment]
I suppose i will try gcc 6.x now?

**Comment by jdlovins** [comment]
That failed too. :( 

Am I crazy for this not working or am I doing something wrong?

I appreciate you taking the time to help me.

**Comment by AnAkkk** [comment]
It might be that they are forcing the old ABI on Ubuntu 14.04, even with newer gcc versions. They probably switch to the new one on more recent versions of Ubuntu.

**Comment by jdlovins** [comment]
Should i try compiling it on a newer ubuntu version then?

**Comment by AnAkkk** [comment]
Yes, well you can actually upgrade Ubuntu 14.04 to 16.04 if you don't want to reinstall everything:
http://www.omgubuntu.co.uk/2016/04/how-to-upgrade-ubuntu-14-04-to-ubuntu-16-04-lts

**Comment by jdlovins** [comment]
well i dont mind making a VM to compile it, but would it run on 14.04 if compiled on 16.04?

**Comment by AnAkkk** [comment]
Yes, the libraries are compiled statically in the plugin.

**Comment by jdlovins** [comment]
Alright! I will try compiling with gcc/++ 6 and libstdc6 and report back what happens. Thanks for all the help thus far.

**Comment by jdlovins** [comment]
Success! It is all working now. Thanks a ton for your help :) All i actually needed it for was the bhop function lol.

**Comment by jdlovins** [comment]
Last question; What is the auto updater? It updates the tftrue.so extension I think from what i see in the  code. I'm not entirely too familiar with C++ so what would be the best way to disable it?

**Comment by AnAkkk** [comment]
You can #define NO_AUTOUPDATE like it is in TFTrue.cpp when compiling a debug build.
