### ISSUE TITLE
So, TFTrue seems to crash my server entirely.

### ISSUE THREAD

**Issue by Umbrozium** [AnAkkk/TFTrue#52]
The server loads as normal at first, but then gives me this error:

Unable to load plugin "addons/metamod/bin/win64/server"
Error Code 31
Failed to load plugin "addons/TFTrue"

After this error, the server's console ceases activity.
Yes, I'm using a Windows 10 TF2 Server, since I'm also using TF2 Server Manager Application. Is there any way to fix this issue?
What other info do I have to provide to clear things out?

**Comment by sapphonie** [comment]
Try version 4.85

**Comment by Umbrozium** [comment]
> Try version 4.85

I did, the server still crashes, but differently than before.

**Comment by Umbrozium** [comment]
I deleted the vdf file, so tftrue wasnt even loaded the whole time. My lack of attention amazes me sometimes. Well, the issue is still there, it still crashes the server. No plugins that could interfere, nothing that implies that it has a conflict with something in the server files. Not even a log.

**Comment by AnAkkk** [comment]
Could you please provide a crash dump?

**Comment by Umbrozium** [comment]
> Could you please provide a crash dump?

Is it in dumps folder?

**Comment by AnAkkk** [comment]
Yes, it should be.

**Comment by Umbrozium** [comment]
It's empty.

**Comment by AnAkkk** [comment]
> It's empty.

What's the console output when your server crashes?

**Comment by Umbrozium** [comment]
It loads like usual, showing some errors unrelated to the plugin, and just after the message "Server is hibernating" it immediately shuts down.

**Comment by AnAkkk** [comment]
Please copy paste the full output so I can have a look.

**Comment by Umbrozium** [comment]
> Please copy paste the full output so I can have a look.

The output of the server when it's loading?

**Comment by Umbrozium** [comment]
Console initialized.
Using Breakpad minidump system. Version: 6848227 AppID: 232250
Loaded 10391 VPK file hashes from O:\GAMES\TF2 Server\Servers\Clayron\Server\tf\tf2_textures.vpk for pure server operation.
Loaded 10391 VPK file hashes from O:\GAMES\TF2 Server\Servers\Clayron\Server\tf\tf2_textures.vpk for pure server operation.
Loaded 478 VPK file hashes from O:\GAMES\TF2 Server\Servers\Clayron\Server\tf\tf2_sound_vo_english.vpk for pure server operation.
Loaded 478 VPK file hashes from O:\GAMES\TF2 Server\Servers\Clayron\Server\tf\tf2_sound_vo_english.vpk for pure server operation.
Loaded 1343 VPK file hashes from O:\GAMES\TF2 Server\Servers\Clayron\Server\tf\tf2_sound_misc.vpk for pure server operation.
Loaded 1343 VPK file hashes from O:\GAMES\TF2 Server\Servers\Clayron\Server\tf\tf2_sound_misc.vpk for pure server operation.
Loaded 2680 VPK file hashes from O:\GAMES\TF2 Server\Servers\Clayron\Server\tf\tf2_misc.vpk for pure server operation.
Loaded 2680 VPK file hashes from O:\GAMES\TF2 Server\Servers\Clayron\Server\tf\tf2_misc.vpk for pure server operation.
Loaded 2680 VPK file hashes from O:\GAMES\TF2 Server\Servers\Clayron\Server\tf\tf2_misc.vpk for pure server operation.
Loaded 1217 VPK file hashes from O:\GAMES\TF2 Server\Servers\Clayron\Server\hl2\hl2_textures.vpk for pure server operation.
Loaded 574 VPK file hashes from O:\GAMES\TF2 Server\Servers\Clayron\Server\hl2\hl2_sound_vo_english.vpk for pure server operation.
Loaded 383 VPK file hashes from O:\GAMES\TF2 Server\Servers\Clayron\Server\hl2\hl2_sound_misc.vpk for pure server operation.
Loaded 451 VPK file hashes from O:\GAMES\TF2 Server\Servers\Clayron\Server\hl2\hl2_misc.vpk for pure server operation.
Loaded 451 VPK file hashes from O:\GAMES\TF2 Server\Servers\Clayron\Server\hl2\hl2_misc.vpk for pure server operation.
Loaded 5 VPK file hashes from O:\GAMES\TF2 Server\Servers\Clayron\Server\platform\platform_misc.vpk for pure server operation.
Loaded 5 VPK file hashes from O:\GAMES\TF2 Server\Servers\Clayron\Server\platform\platform_misc.vpk for pure server operation.
server.dll loaded for "Team Fortress"
For FCVAR_REPLICATED, ConVar must be defined in client and game .dlls (sv_use_steam_voice)
ProtoDefs post data loaded.
ProtoDefs loaded. 27.27 MB used
ProtoDefs post data loaded.
ProtoDefs loaded. 27.27 MB used
Unable to load plugin "addons/metamod/bin/win64/server"
[TFTrue] tftrue_whitelist_id = -1! mp_tournament_whitelist updated, reloading whitelist!
[TFTrue] -> Using mp_tournament_whitelist as tftrue_whitelist_id is unset...
Item Whitelist file 'item_whitelist.txt' could not be found. All items will be allowed.
maxplayers set to 12
No '-replayserverdir' parameter found - using default replay folder.
Replay: Creating thread pool...succeeded.
Replay: Starting thread pool with 4 threads...succeeded.
Cleaning files from temp dir, "o:\games\tf2 server\servers\clayron\server\tf\replay\server\tmp\" ...no files removed.
ProtoDefs post data loaded.
ProtoDefs post data loaded.
Unknown command "r_decal_cullsize"
maxplayers set to 12
Network: IP 0.0.0.0, mode MP, dedicated Yes, ports 27016 SV / 27021 CL
Initializing Steam libraries for secure Internet server
No account token specified; logging into anonymous game server account.  (Use sv_setsteamaccount to login to a persistent account.)
SOLID_VPHYSICS static prop with no vphysics model! (models/props_spytech/radio_tower001.mdl)
L 10/26/2021 - 15:02:54: [stac.smx] [StAC] File handle invalid!
L 10/26/2021 - 15:02:54: [stac.smx] [StAC] Plugin vers. ---- 5.1.0 ---- loaded
Executing dedicated server config file server.cfg
Using map cycle file 'cfg/mapcycle_default.txt'.  ('cfg\mapcycle.txt' was not found.)
material models/weapons/c_items/c_ubersaw_xms has a normal map and $basealphaenvmapmask.  Must use $normalmapalphaenvmapmask to get specular.

material models/weapons/c_items/c_frontierjustice_xmas has a normal map and $basealphaenvmapmask.  Must use $normalmapalphaenvmapmask to get specular.

material models/player/items/all_class/all_class_ring_setting has a normal map and $basealphaenvmapmask.  Must use $normalmapalphaenvmapmask to get specular.

material models/player/items/crafting/coin_invasion has a normal map and $basealphaenvmapmask.  Must use $normalmapalphaenvmapmask to get specular.

Item Whitelist file 'item_whitelist.txt' could not be found. All items will be allowed.
Set motd from file 'cfg/motd_default.txt'.  ('cfg/motd.txt' was not found.)
Set motd_text from file 'cfg/motd_text_default.txt'.  ('cfg/motd_text.txt' was not found.)
SV_ActivateServer: setting tickrate to 66.7
Connection to game coordinator established.
Current item schema is up-to-date with version 9908715C.
'server.cfg' not present; not executing.
'cp_process_final.cfg' not present; not executing.
Item Whitelist file 'item_whitelist.txt' could not be found. All items will be allowed.
[SM] Plugin antiflood.smx is already loaded.
[SM] Plugin basetriggers.smx is already loaded.
[SM] Plugin basevotes.smx is already loaded.
[SM] Plugin funcommands.smx is already loaded.
[SM] Plugin funvotes.smx is already loaded.
[SM] Plugin playercommands.smx is already loaded.
[SM] Plugin soap_tf2dm.smx is already loaded.
[SM] Plugin sounds.smx is already loaded.
[SM] Plugin antiflood.smx is already loaded.
[SM] Plugin basetriggers.smx is already loaded.
[SM] Plugin basevotes.smx is already loaded.
[SM] Plugin funcommands.smx is already loaded.
[SM] Plugin funvotes.smx is already loaded.
[SM] Plugin playercommands.smx is already loaded.
[SM] Plugin soap_tf2dm.smx is already loaded.
[SM] Plugin sounds.smx is already loaded.
Server is hibernating

**Comment by AnAkkk** [comment]
This doesn't seem to show any sort of crash? The plugin loads fine without any errors according to this console output. There are just errors related to metamod.

**Comment by Umbrozium** [comment]
> This doesn't seem to show any sort of crash? The plugin loads fine without any errors according to this console output. There are just errors related to metamod.

It's the latest stable build of Metamod, I don't know what's the problem with it.

**Comment by Umbrozium** [comment]
https://user-images.githubusercontent.com/38528831/138849978-907dee74-afd3-4ece-ac61-5ea69d95cdc3.mp4

Just to show what happens to the server.

**Comment by AnAkkk** [comment]
Could you try to remove Metamod/Sourcemod and check if it is still crashing?
Where did you download the version of TFTrue you are using from?

**Comment by Umbrozium** [comment]
> Could you try to remove Metamod/Sourcemod and check if it is still crashing? Where did you download the version of TFTrue you are using from?

I'm using the TFTrue version downloaded from here on Github. I got the archive with the source code and got the compiled dll from the releases folder. Then I got the vdf file from the archive that was on the esports tools website.

**Comment by Umbrozium** [comment]
https://user-images.githubusercontent.com/38528831/138852146-adc86131-7ee9-484f-8e24-5d582e4ec572.mp4

This happened when I removed Sourcemod and Metamod.

**Comment by AnAkkk** [comment]
Try https://github.com/AnAkkk/TFTrue/blob/public/release/TFTrue.dll

**Comment by Umbrozium** [comment]
I think it's working! It didn't show this message before.
![image](https://user-images.githubusercontent.com/38528831/138880265-cfec4cb1-fdb9-42a4-96f9-dfb3aa6278e2.png)

**Comment by Umbrozium** [comment]
Could TFTrue be conflicting with any of these plugins?
[SM] Plugin antiflood.smx is already loaded.
[SM] Plugin basetriggers.smx is already loaded.
[SM] Plugin basevotes.smx is already loaded.
[SM] Plugin funcommands.smx is already loaded.
[SM] Plugin funvotes.smx is already loaded.
[SM] Plugin playercommands.smx is already loaded.
[SM] Plugin soap_tf2dm.smx is already loaded.
[SM] Plugin sounds.smx is already loaded.
[SM] Plugin antiflood.smx is already loaded.
[SM] Plugin basetriggers.smx is already loaded.
[SM] Plugin basevotes.smx is already loaded.
[SM] Plugin funcommands.smx is already loaded.
[SM] Plugin funvotes.smx is already loaded.
[SM] Plugin playercommands.smx is already loaded.
[SM] Plugin soap_tf2dm.smx is already loaded.
[SM] Plugin sounds.smx is already loaded.

I'm asking because even though the server did not crash right away, when I connected to it, joined a team, and then picked a class, after walking around and shooting for a bit, the server crashed again.

**Comment by Umbrozium** [comment]
> Could TFTrue be conflicting with any of these plugins? [SM] Plugin antiflood.smx is already loaded. [SM] Plugin basetriggers.smx is already loaded. [SM] Plugin basevotes.smx is already loaded. [SM] Plugin funcommands.smx is already loaded. [SM] Plugin funvotes.smx is already loaded. [SM] Plugin playercommands.smx is already loaded. [SM] Plugin soap_tf2dm.smx is already loaded. [SM] Plugin sounds.smx is already loaded. [SM] Plugin antiflood.smx is already loaded. [SM] Plugin basetriggers.smx is already loaded. [SM] Plugin basevotes.smx is already loaded. [SM] Plugin funcommands.smx is already loaded. [SM] Plugin funvotes.smx is already loaded. [SM] Plugin playercommands.smx is already loaded. [SM] Plugin soap_tf2dm.smx is already loaded. [SM] Plugin sounds.smx is already loaded.
> 
> I'm asking because even though the server did not crash right away, when I connected to it, joined a team, and then picked a class, after walking around and shooting for a bit, the server crashed again.

Nevermind, I removed all plugins and I'm still crashing as soon as I spawn on the server.
However, the plugin loads correctly and all cvars are available to change.
EDIT: Tested again, this time removing both Metamod and Sourcemod. Again, it loads correctly, but as soon as I join, pick a team and class, spawn in the server, it crashes.

**Comment by AnAkkk** [comment]
> 
> 
> > Could TFTrue be conflicting with any of these plugins? [SM] Plugin antiflood.smx is already loaded. [SM] Plugin basetriggers.smx is already loaded. [SM] Plugin basevotes.smx is already loaded. [SM] Plugin funcommands.smx is already loaded. [SM] Plugin funvotes.smx is already loaded. [SM] Plugin playercommands.smx is already loaded. [SM] Plugin soap_tf2dm.smx is already loaded. [SM] Plugin sounds.smx is already loaded. [SM] Plugin antiflood.smx is already loaded. [SM] Plugin basetriggers.smx is already loaded. [SM] Plugin basevotes.smx is already loaded. [SM] Plugin funcommands.smx is already loaded. [SM] Plugin funvotes.smx is already loaded. [SM] Plugin playercommands.smx is already loaded. [SM] Plugin soap_tf2dm.smx is already loaded. [SM] Plugin sounds.smx is already loaded.
> > I'm asking because even though the server did not crash right away, when I connected to it, joined a team, and then picked a class, after walking around and shooting for a bit, the server crashed again.
> 
> Nevermind, I removed all plugins and I'm still crashing as soon as I spawn on the server. However, the plugin loads correctly and all cvars are available to change. EDIT: Tested again, this time removing both Metamod and Sourcemod. Again, it loads correctly, but as soon as I join, pick a team and class, spawn in the server, it crashes.

I can't reproduce this. What are your server settings?

I've rebuilt again, some of the last changes were missing: https://github.com/AnAkkk/TFTrue/blob/public/release/TFTrue.dll
Let me know if that fixes anything.

**Comment by Umbrozium** [comment]
How exactly can I collect my server settings so I can upload them here?

**Comment by AnAkkk** [comment]
I meant whatever you have put in server.cfg or other config files. You could also try to type `differences` in the server console before it crashes to get the list of cvars with non default values.

Did you try the new file?

**Comment by Umbrozium** [comment]
I just put it in the addons, I'm going to test it out right now.

**Comment by Umbrozium** [comment]
I typed in differences, here's what I got:
"jay_backtrack_tolerance" = "1" ( def. "0" ) min. 0.000000 max. 3.000000
 - Tolerance for tickcount changes.
0 = Tickcount must increment.
N+ = Tickcount can be off by N ticks (Don't go higher than 2).
"sm_timeleft_interval" = "0" ( def. "0.0" ) min. 0.000000 max. 1800.000000
 - Display timeleft every x seconds. Default 0.
"sm_nextmap" = "cp_dustbowl" ( def. "" )
 notify
"metamod_version" = "1.11.0-dev+1145V" ( def. "1.11.0-dev+1145" )
 notify singleplayer
 - Metamod:Source Version
"sv_skyname" = "sky_jungle_01" ( def. "sky_urb01" )
 game archive replicated
 - Current name of the skybox texture
"think_limit" = "0" ( def. "10" )
 game replicated
 - Maximum think time in milliseconds, warning is printed if this is exceeded.
"sv_maxusrcmdprocessticks" = "16" ( def. "24" )
 game notify
 - Maximum number of client-issued usrcmd ticks that can be replayed in packet loss conditions, 0 to allow no restrictions
"sv_turbophysics" = "1" ( def. "0" )
 game replicated
 - Turns on turbo physics
"mp_tournament_readymode_countdown" = "5" ( def. "10" )
 game notify replicated
 - The number of seconds before a match begins when both teams are ready.
"sv_unlockedchapters" = "99" ( def. "1" )
 archive
 - Highest unlocked game chapter.
"mat_texture_list_all" = "0"
 cheat
 - If this is nonzero, then the texture list panel will show all currently-loaded textures.
"mat_texture_list_view" = "1"
 cheat
 - If this is nonzero, then the texture list panel will render thumbnails of currently-loaded textures.
"mat_show_texture_memory_usage" = "0"
 cheat
 - Display the texture memory usage on the HUD.
"rcon_password" = "crybaby" ( def. "" )
 - remote console password.
"sv_region" = "255" ( def. "-1" )
 - The region of the world to report this server in.
"sv_tags" = "cp" ( def. "" )
 notify
 - Server tags. Used to provide extra information to clients when they're browsing for servers. Separate tags with a comma.
"tv_maxrate" = "0" ( def. "8000" )
 - Max SourceTV spectator bandwidth rate allowed, 0 == unlimited
"tv_snapshotrate" = "66" ( def. "16" )
 - Snapshots broadcasted per second
"deathmatch" = "1" ( def. "0" )
 notify
 - Running a deathmatch server.
"hostname" = "byblank's competitive lan server" ( def. "" )
 - Hostname for server.
"host_map" = "ultiduo_baloo" ( def. "" )
 - Current map name.
"ip" = "0.0.0.0" ( def. "localhost" )
 - Overrides IP for multihomed hosts
"hostport" = "27017" ( def. "27015" )
 - Host game server port
"clientport" = "27022" ( def. "27005" )
 - Host game client port
"datacachesize" = "256" ( def. "64" ) min. 32.000000 max. 512.000000
 - Size in MB.
"r_flashlightdepthtexture" = "0" ( def. "1" )

**Comment by Umbrozium** [comment]
I joined my server, and it didn't crash. I also tested out the whitelist cvar, which seems to be working as it should. Maybe some new features are conflicting with other plugins on my server?

**Comment by AnAkkk** [comment]
So everything is working fine now with the latest build, right? If so, I will just close this ticket.

**Comment by Umbrozium** [comment]
> So everything is working fine now with the latest build, right? If so, I will just close this ticket.

Yeah, everything works pretty much.
EDIT: Everything, except pausing, which I didn't think of trying before, but I guess it's good that I did, because pausing crashes the server. I was using the etf2l_ultiduo configuration, joined the server and used the pause command.

**Comment by sapphonie** [comment]
@Umbrozium this is likely a sourcemod issue (aka, update your sourcemod to latest version), not a TFTrue one. If you can get a crash report with Accelerator, a crash reporting service for servers running sourcemod (https://forums.alliedmods.net/showthread.php?t=277703&), and it points to TFTrue, please open an issue. Otherwise, this should be closed.

**Comment by Umbrozium** [comment]
> @Umbrozium this is likely a sourcemod issue (aka, update your sourcemod to latest version), not a TFTrue one. If you can get a crash report with Accelerator, a crash reporting service for servers running sourcemod (https://forums.alliedmods.net/showthread.php?t=277703&), and it points to TFTrue, please open an issue. Otherwise, this should be closed.

Okay, so I updated Sourcemod, and then the new TF2 update came out so I updated the server as well. Then I joined it, and it basically crashed seconds later, without me doing anything besides moving around the map. As you requested me to do, I used Accelerator, and after the crash I relaunched the server so the dump would be uploaded to Throttle. Here's the link to it: https://crash.limetech.org/pbqpdqlhqty6
As I mentioned before, I'm using the cvar and whitelist set from etf2l_ultiduo.

**Comment by sapphonie** [comment]
Interesting. I'll take a look now.

**Comment by sapphonie** [comment]
This might be related to Valve changing the status command.

Here's a func graph of the crash:
![image](https://user-images.githubusercontent.com/15315481/139196434-34679c62-16d4-416d-ace3-bf4a77e7114b.png)

In function `0x14df0`

My money is on this being the status command callback:

https://github.com/AnAkkk/TFTrue/blob/bb34c7f3ce546cca4fc91aefe9f8644be1a2329d/tournament.cpp#L513

![image](https://user-images.githubusercontent.com/15315481/139196761-6497fac7-1074-4f7d-9dfe-3045dc306450.png)


`mp_tournament`
`tf_gamemode_mvm`
`plugin_print`

**Comment by sapphonie** [comment]
Maybe `cmd_clientslot` is wrong?

https://github.com/AnAkkk/TFTrue/blob/bb34c7f3ce546cca4fc91aefe9f8644be1a2329d/tournament.cpp#L133-L134

**Comment by Umbrozium** [comment]
Um, I don't quite understand what this means. is cmd_clientslot a cvar or a command, or is it something that has to be changed in the plugin?

**Comment by sapphonie** [comment]
Don't worry about it, it's a plugin issue. I'll try to get a fix going, if not, AnAkkk will probably have to take a crack at it.

**Comment by AnAkkk** [comment]
The fix from @sapphonie seems to work, it doesn't crash at all for me. @Umbrozium I've pushed a new build https://github.com/AnAkkk/TFTrue/blob/public/release/TFTrue.dll

**Comment by Umbrozium** [comment]
> The fix from @sapphonie seems to work, it doesn't crash at all for me. @Umbrozium I've pushed a new build https://github.com/AnAkkk/TFTrue/blob/public/release/TFTrue.dll

The server did not crash when I joined, nor did it crash when I paused it. I checked some other commands too, but I'll give you a full report in a bit.

**Comment by Umbrozium** [comment]
> > The fix from @sapphonie seems to work, it doesn't crash at all for me. @Umbrozium I've pushed a new build https://github.com/AnAkkk/TFTrue/blob/public/release/TFTrue.dll
> 
> The server did not crash when I joined, nor did it crash when I paused it. I checked some other commands too, but I'll give you a full report in a bit.

Alright, I'm positive that everything works correctly, guess it's time to close the issue.
