### ISSUE TITLE
creating a release on github

### ISSUE THREAD

**Issue by Spaenny** [AnAkkk/TFTrue#53]
I think it would be benefical to create a release after a travis build, currently nightly builds for docker container who use checksums fail because it getting updated. (See here https://github.com/melkortf/tf2-servers/pull/7) 

This would be solved if there is a release tag.
I have no clue of Travis, but adding:

See #55

in the after_success group should do the trick correct?

**Comment by garrappachc** [comment]
+1 to that. Versioning the builds in any way and making them part of GitHub releases is the preferred way.

**Comment by sapphonie** [comment]
+1, please do this
