### ISSUE TITLE
logging for crossbow heals

### ISSUE THREAD

**Issue by CondensedTea** [AnAkkk/TFTrue#57]
I want to try adding logging for crossbow heals.

Am I correct it can be achived with adding another `else if` case [here](https://github.com/AnAkkk/TFTrue/blob/public/logs.cpp#L518-L531) for event [crossbow_heal](https://wiki.alliedmods.net/Team_Fortress_2_Events#crossbow_heal)?

**Comment by sapphonie** [comment]
is this not already accomplished with `player_healonhit`

**Comment by CondensedTea** [comment]
My goal is to add crossbow heals to logs.tf medic's summaries, but their parser uses only `player_healed` events
