### ISSUE TITLE
broken with 06/21/22 tf2 update

### ISSUE THREAD

**Issue by sapphonie** [AnAkkk/TFTrue#70]
https://github.com/dalegaard/srctvplus/issues/2 - bump gameserverinterface vers

might be more in depth than that tho 😛

**Comment by douglasb78** [comment]
> might be more in depth than that tho 😛

Maybe TF2True relies on stats screen data to upload matches to logs.tf?
The latest update changed a bug where "%killername%" appeared instead of the actual player name in there.
I don't know, it's a blind guess.

https://github.com/AnAkkk/TFTrue/blob/public/stats.cpp

~ just a fellow tf2 player

**Comment by AnAkkk** [comment]
The linux build was already fixed, I still need to recompile the windows one.

**Comment by kikaragyozov** [comment]
@AnAkkk Latest version for some reason doesn't do anything when ran on Linux.

**Comment by AnAkkk** [comment]
Did you download the latest release or the binary here https://github.com/AnAkkk/TFTrue/tree/public/release?

**Comment by AnAkkk** [comment]
Updated binaries.
