### ISSUE TITLE
Newest Valve update will break TFTrue.

### ISSUE THREAD

**Issue by bartico6** [AnAkkk/TFTrue#8]
I've tested a server with nothing but TFTrue on the prerelease beta branch - Valve plans to change the toolkit used to compile the game - it's available as a beta branch to download and test.
Run SteamCMD and force an update with this command:
>app_update 232250 -beta toolchainbeta

Then attempt to start a server with TFTrue - the server will segfault.

Please make sure it's supported for the newest beta (it may be upstream as soon as next week!!!) - the server doesn't even start up with TFTrue installed and it's widely used in all tf2 leagues.

If further information is needed, I'm available [here](http://steamcommunity.com/id/bartico6)

**Comment by AnAkkk** [comment]
Didn't have time to look into it, I will look into it now.

**Comment by AnAkkk** [comment]
I pushed some fixes and updated https://tftrue.esport-tools.net/TFTrue.so
Autoupdate will not work right now, there is an issue with the host.
Some features like the class limits without mp_tournament do not work right now, but it seems like there is tf_classlimits that does a similar thing anyway.

**Comment by garrappachc** [comment]
Any chance to have whitelists fixed?

**Comment by AnAkkk** [comment]
What is wrong with the whitelists?

**Comment by garrappachc** [comment]
They don't work.

**Comment by garrappachc** [comment]
Sorry, I didn't  specify: whitelists don't work without mp_tournament set to 1. It used to work before the update.
EDIT: Whitelists don't work with mp_tournament set to 1 as well. Just noticed. Dunno what's wrong about it.

**Comment by garrappachc** [comment]
It seems like mp_tournament_whitelist is read properly, but blacklisted weapons aren't replaced anyway...

**Comment by garrappachc** [comment]
#9 seems to be fixing the issue, but please let me know whether I broke something else I'm not aware of.

**Comment by AnAkkk** [comment]
Pushed some fixes for the linux and windows versions:
https://tftrue.esport-tools.net/TFTrue.dll
https://tftrue.esport-tools.net/TFTrue.so

The auto update will not work yet though.

**Comment by AnAkkk** [comment]
Auto update should be fixed as well now, same download URL.
