### ISSUE TITLE
Server crashes on any damage

### ISSUE THREAD

**Issue by lightmanLP** [AnAkkk/TFTrue#83]
I have pretty same issue https://www.teamfortress.tv/post/314032/tftrue
Im using [latest release](https://github.com/AnAkkk/TFTrue/tree/public/release).
[crash_20230118183842_2.dmp.zip](https://github.com/AnAkkk/TFTrue/files/10445577/crash_20230118183842_2.dmp.zip)

**Comment by lightmanLP** [comment]
I also found stack trace with accelerator plugin
https://crash.limetech.org/hrw55fapogse

**Comment by AnAkkk** [comment]
Hi, sorry for the late reply. I have pushed some new builds in the repo, could you let me know if that fixes the issue?

**Comment by lightmanLP** [comment]
Seems like fixed, thanks.
